name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: startpage

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --label "runnumber=${GITHUB_RUN_ID}"
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        TIMESTAMP=$(date +%s)

        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        [ "$VERSION" == "main" ] && VERSION=latest

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        echo TIMESTAMP=$TIMESTAMP
        
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$TIMESTAMP
        
        docker push $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$TIMESTAMP
